{{- with .Values.imageCredentials }}
{{- if and .registry .username .password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cbctf.fullname" $ }}-registry
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "cbctf.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}"
    .registry .username .password (printf "%s:%s" .username .password | b64enc) | quote }}
{{- end }}
{{- end }}
